// <auto-generated />
using BotDeScans.App.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BotDeScans.App.Infra.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250910201052_SkipSteps")]
    partial class SkipSteps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("BotDeScans.App.Models.Entities.SkipStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Step")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TitleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TitleId");

                    b.ToTable("SkipSteps");
                });

            modelBuilder.Entity("BotDeScans.App.Models.Entities.Title", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("DiscordRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("BotDeScans.App.Models.Entities.TitleReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Key")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TitleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TitleId", "Key")
                        .IsUnique();

                    b.ToTable("TitleReferences");
                });

            modelBuilder.Entity("BotDeScans.App.Models.Entities.SkipStep", b =>
                {
                    b.HasOne("BotDeScans.App.Models.Entities.Title", "Title")
                        .WithMany("SkipSteps")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Title");
                });

            modelBuilder.Entity("BotDeScans.App.Models.Entities.TitleReference", b =>
                {
                    b.HasOne("BotDeScans.App.Models.Entities.Title", "Title")
                        .WithMany("References")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Title");
                });

            modelBuilder.Entity("BotDeScans.App.Models.Entities.Title", b =>
                {
                    b.Navigation("References");

                    b.Navigation("SkipSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
